#!/usr/bin/perl -w

use strict;


### Load Packages & Modules ####################################################
use strict;
#use Cwd;
#use Fcntl;
use IO::Handle;
use Math::Trig;
use FindBin qw($RealBin); # Absolute path to THIS script.
use lib $RealBin . "/modules";
autoflush STDOUT 1; # For direct output (IO:Handle).

use Math::Trig;
use vector;
use FileIO::gro;
#use protein;
################################################################################



### Default Parameters #########################################################
our $verbose      = 0;                  # Be loud and noisy (and global).

my $inFile  = 'in1.gro';
my $outFile = 'out.dat';
################################################################################



### Internal parameters ########################################################
my %inFileData;         # Filled by "GROFiles::readGro(<GROFILE>)".

my %geoCenterVec;
my %zMaxVec;
################################################################################



### Commandline-Parameters #####################################################
my %cmdLParam = ('f'          => \$inFile,
                 'o'          => \$outFile,
                 'v=f'        => \$verbose,
                 'NOPARAM'    => \&printHelp,
                 'UNKNOWN'    => \&printHelp,
                 'help=f'     => \&printHelp,
                 '?=f'        => \&printHelp,
                 'h=f'        => \&printHelp);
cmdlineParser(\%cmdLParam);
################################################################################



### Read the GRO files #########################################################
%inFileData = GRO::readGro($inFile); # Read input GRO file.
for (my $i=1; $i<@{$inFileData{'atoms'}}; $i++) {
    next unless $inFileData{'atoms'}[$i]{'atomName'};
    next unless $inFileData{'atoms'}[$i]{'atomName'} eq 'CEN';
    $geoCenterVec{'cooX'} = $inFileData{'atoms'}[$i]{'cooX'};
    $geoCenterVec{'cooY'} = $inFileData{'atoms'}[$i]{'cooY'};
    $geoCenterVec{'cooZ'} = $inFileData{'atoms'}[$i]{'cooZ'};
    $i = @{$inFileData{'atoms'}}; # Jump out.
}

for (my $i=1; $i<@{$inFileData{'atoms'}}; $i++) {
    next unless $inFileData{'atoms'}[$i]{'resName'};
    next unless $inFileData{'atoms'}[$i]{'resName'} eq 'DUM';
    next unless $inFileData{'atoms'}[$i]{'atomName'} eq 'MID';
    unless (defined $zMaxVec{'cooZ'}) {
        $zMaxVec{'cooX'} = $inFileData{'atoms'}[$i]{'cooX'};
        $zMaxVec{'cooY'} = $inFileData{'atoms'}[$i]{'cooY'};
        $zMaxVec{'cooZ'} = $inFileData{'atoms'}[$i]{'cooZ'};
    }
    if ($inFileData{'atoms'}[$i]{'cooZ'} > $zMaxVec{'cooZ'}) {
        $zMaxVec{'cooX'} = $inFileData{'atoms'}[$i]{'cooX'};
        $zMaxVec{'cooY'} = $inFileData{'atoms'}[$i]{'cooY'};
        $zMaxVec{'cooZ'} = $inFileData{'atoms'}[$i]{'cooZ'};
    }
}
#print "... $geoCenterVec{'cooZ'} $zMaxVec{'cooZ'}\n";

### Calculate the angle of the dummy atom axis to zero #########################
#$geoCenterVec{'cooZ'} = 0 - $geoCenterVec{'cooZ'};
#$zMaxVec{'cooZ'} = (0  - $geoCenterVec{'cooZ'}) - $zMaxVec{'cooZ'};

my %point = ('cooX' => $zMaxVec{'cooX'},
             'cooY' => $zMaxVec{'cooY'},
             'cooZ' => $geoCenterVec{'cooZ'});

my %ankathete = Vector::vSub(\%point, \%geoCenterVec);
my %gegenkathete = Vector::vSub(\%zMaxVec, \%point);
print "Gegenkathete: " . Vector::vLen(\%gegenkathete) . "\n";
print "Ankathete:    " .  Vector::vLen(\%ankathete) . "\n";
my $alpha = rad2deg(atan(Vector::vLen(\%gegenkathete)/Vector::vLen(\%ankathete)));
print "Alpha:        " . $alpha . "\n";
################################################################################


#open(OUTFILE, ">$outFile") || die "ERROR: Cannot open output file \"$outFile\": $!\n";
#print OUTFILE "$zCenter\n$zMax\n";
#close(OUTFILE);
#GRO::writeGro($outFile, \%inFileData);

#`echo 3 | g_rms -s $outFile1 -f $outFile2 -fit none -o $outRmsd`;
################################################################################






sub printHelp {
    print "
###########################################################################
                                 LAMBADA
                     Written by Christian Kandt, (c) 2012

   Kandt C, Ash WL, Tieleman DP (2007): Setting up and running molecular
       dynamics simulations of membrane proteins. Methods 41:475-488

                     http://www.csb.bit.uni-bonn.de
###########################################################################

INFLATEGRO reads the coordinates of a bilayer and inflates them in XY
directions using a common SCALING FACTOR. To identify the lipids for
inflating a group in an NDX file must be defined.

Everything else will be centered in the XY plane of the new simulation box.

A DISTANCE CUTOFF in nm can be defined: Only lipids with a P - CA distance
exceeding that cutoff will be written. It is currently assumed that you're
actually dealing with phospholipids. However, this can be easily changed in
the code.

AREA PER LIPID is estimated by caculating the area per protein first.
This is done using a grid-based approach. A GRID SIZE of 5 A (0.5 nm) was
found to give good results. Output is written as a 3-collumned ASCII file
holding three area per lipid values: total, upper leaflet & lower leaflet.

DOUGHNUT mode is a recent extension to INFLATEGRO that might be useful when
dealing with several peptides at once or multimeric proteins of somewhat
torrodial (doughnut-like!) shape featuring central lipid-filled cavities.
It is activated via the >doughnut< flag. If that is set, the protein is no
longer centered in the XY plane. Instead, inflating now also applies to the
protein coordinates which are translated laterally in a subunit-dependent
manner. Protein subunits are defined in an given ndx file.

USAGE: lambada --igro INPUTGROFILE --ogro OUTPUTGROFILE
  --igro             Input GRO file (default: \"\").
  --ogro             Output GRO file (default: \"\").
  -g                 Grid size to detect the area of the protein [nm]  (default: \"\").
  -v                 Be loud and noisy and communicative and meaningful and profound. Seriously!
  -h, -? or --help   Put out this help.\n\n";
    exit;
}



sub cmdlineParser {
    my $paramsRef = shift;

    my %knownParam;
    my @unknownParam;

    for (my $argID=0; $argID<@ARGV; $argID++) {
        my $cmdlineName = $ARGV[$argID];
        $knownParam{$ARGV[$argID]} = 0;

        foreach my $paramKey (keys %{$paramsRef}) {
            my $paramName = $paramKey;
            my $paramType = 0;
            my $paramIni  = "--";
            my $isArray   = 0;

            if ($paramKey =~ /^(.+?)=([\@f])$/) {
                $paramName = $1;
                $paramType = $2;
            }

            $paramIni = "-" if (length($paramName) == 1);

            if ($paramType eq "@") {
                $isArray = 1;
            }
            elsif ($paramType eq "f") {
                if ($cmdlineName eq $paramIni.$paramName) {
                    if (ref(${$paramsRef}{$paramKey}) eq "SCALAR") {
                        ${${$paramsRef}{$paramKey}} = 1;
                        $knownParam{$cmdlineName} = 1;
                    }
                    elsif (ref(${$paramsRef}{$paramKey}) eq "CODE") {
                        &{${$paramsRef}{$paramKey}}();
                        $knownParam{$cmdlineName} = 1;
                    }
                }
                next;
            }

            if ($cmdlineName eq $paramIni.$paramName && not $isArray) {
                $argID++;
                next if($ARGV[$argID] =~ /^-/);

                ${${$paramsRef}{$paramKey}} = $ARGV[$argID];
                $knownParam{$cmdlineName} = 1;
            }
            elsif ($ARGV[$argID] eq $paramIni.$paramName && $isArray) {
                $knownParam{$cmdlineName} = 1;
                $argID++;

                my @tmpArray;
                while ($argID <= $#ARGV && not $ARGV[$argID] =~ /^--/ && not $ARGV[$argID] =~ /^-.$/) {
                    push (@tmpArray, $ARGV[$argID]);
                    $argID++;
                }
                @{${$paramsRef}{$paramKey}} = @tmpArray;
                $argID--;
            }
        }

        if (defined $knownParam{$cmdlineName} && $knownParam{$cmdlineName} == 0) {
            push(@unknownParam, $cmdlineName) if($cmdlineName =~ /^-/);
        }
    }


    ### Catch unknown parameters ###########################
    if (@unknownParam && ${$paramsRef}{"UNKNOWN"} && ref(${$paramsRef}{"UNKNOWN"}) eq "CODE") {
        print "WARNING: Unknown or non-set parameters detected:\n";
        for (@unknownParam) { print "        \"$_\"\n"; }
        &{${$paramsRef}{"UNKNOWN"}}();
    }
    elsif (@unknownParam) {
        print "ERROR: Unknown or non-set parameters detected:\n";
        for(@unknownParam) { print "       \"$_\"\n"; }
        exit;
    }
    ########################################################


    ### Catch no given parameters ##########################
    if (!@ARGV && ${$paramsRef}{"NOPARAM"} && ref(${$paramsRef}{"NOPARAM"}) eq "CODE") {
        print "WARNING: Parameters needed...\n";
        &{${$paramsRef}{"NOPARAM"}}();
    }
    ########################################################
}

