#!/usr/bin/perl -w

# Copyright 2016 Thomas H. Schmidt
#
# This file is part of DanceSteps.
#
# DanceSteps is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# DanceSteps is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with DanceSteps; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


### Load Packages ##############################################################
use strict;
use IO::Handle;
use FindBin qw($RealBin); # Absolute path to THIS script.
use LWP::Simple;
use lib ($RealBin."/modules/FileIO", $RealBin."/modules");
autoflush STDOUT 1; # For direct output.

use Commandline;
use Statistics;
################################################################################



### Default Parameters #########################################################
our $version        = "1";                # Version number.
our $year           = "2016";             # Year (of change).

our $verbose        = 0;                  # Be loud and noisy (and global); default: silent.
our $copyright      = 0;                  # Print copyright information.

my $helpAndQuit     = 0;                  # Print out program help.

my $pdbIdFile       = 'pdbids.txt';       # Input PDB ID list file.
################################################################################



### Internal parameters ########################################################
my @pdbIds;            # Filled by "readPdbListFile(<PDBLISTFILE>)".
################################################################################



### Print out program headlines ################################################
printHead();
################################################################################



### Handle commandline parameters ##############################################
addCmdlParam('scalar', 'f',        'Input',      \$pdbIdFile,        $pdbIdFile, 'PDB ID list file: dat');
addCmdlParam('flag',   'h',        'bool',       \$helpAndQuit,      $helpAndQuit ? 'yes' : 'no', 'Print help info and quit');
addCmdlParam('flag',   'copyright','bool',       \$copyright,        $copyright ? 'yes' : 'no', 'Print copyright information');
addCmdlParam('flag',   'v',        'bool',       \$verbose,          $verbose ? 'yes' : 'no', 'Be loud and noisy');

cmdlParser();
################################################################################



### Print program help if the user set the flag ################################
printHelp(getCmdlParamRef(), 1) if $helpAndQuit;
################################################################################



### 
@pdbIds = readPdbIdFile($pdbIdFile);

my @outputGlobular;
my @outputNonGlobular;

my $pdbFileDir = "pdbfiles";
mkdir($pdbFileDir);

for (my $i=0; $i<@pdbIds; $i++) {
    print $pdbIds[$i]{'id'} . "(" . $pdbIds[$i]{'chain'} . ")";
    my $pdbDownlFile = $pdbFileDir . "/" . $pdbIds[$i]{'id'} . ".pdb";
    my $pdbFile      = $pdbFileDir . "/" . $pdbIds[$i]{'id'} . "_chain" . $pdbIds[$i]{'chain'} . ".pdb";


    ### Download PDB file and extract chains ###################################
    my $tmpUrl = "http://www.rcsb.org/pdb/download/downloadFile.do?fileFormat=pdb&compression=NO&structureId=" . $pdbIds[$i]{'id'};
    getstore($tmpUrl, $pdbDownlFile);
    unless (-e $pdbDownlFile) {
        print " :: WARNING: Could not download PDB-File. Try the next one.\n";
        next;
    }
    system("perl ../extract_chainseq/extract_chainseq -ph $pdbDownlFile >>log.out 2>&1");
    ############################################################################



    ### Analyze using GROMACS ##################################################
    system("echo 0 | gmx gyrate -s $pdbFile -f $pdbFile -o gyrate." . $pdbIds[$i]{'id'} . "_chain" . $pdbIds[$i]{'chain'} . ".xvg -p >>log.out 2>&1");

    my @radii = readGyrateFile("gyrate." . $pdbIds[$i]{'id'} . "_chain" . $pdbIds[$i]{'chain'} . ".xvg");
    my @statistics = Statistics::all(\@radii);
#    print "  $radii[0] $radii[1] $radii[2] :: mean = $statistics[0] +/-$statistics[2] nm\n";


    system("echo 0 | gmx sasa -s $pdbFile -f $pdbFile -tv volume." . $pdbIds[$i]{'id'} . "_chain" . $pdbIds[$i]{'chain'} . ".xvg >>log.out 2>&1");
    system("rm area.xvg");

    my $PI = 3.1415926;
    my $volume = readVolumeFile("volume." . $pdbIds[$i]{'id'} . "_chain" . $pdbIds[$i]{'chain'} . ".xvg");
    my $radiusOfVol = (0.75*$volume/$PI)**(1/3);
    my $areaOfRadius = $PI*$radiusOfVol*$radiusOfVol;

    if ($statistics[2] > 0.15) {
        print " :: NOT GLOBULAR (STDDEV = $statistics[2] nm)\n";

        push(@outputNonGlobular, buildHash($pdbIds[$i]{'id'},
                                        $pdbIds[$i]{'chain'},
                                        $radii[0],      # Radius of gyration to x-axis.
                                        $radii[1],      # Radius of gyration to y-axis.
                                        $radii[2],      # Radius of gyration to z-axis.
                                        $statistics[0], # Mean.
                                        $statistics[2], # STDDEV.
                                        $volume,
                                        $radiusOfVol,
                                        $areaOfRadius));
    }
    else {
        print " :: GLOBULAR (STDDEV = $statistics[2] nm)\n";

        push(@outputGlobular, buildHash($pdbIds[$i]{'id'},
                                        $pdbIds[$i]{'chain'},
                                        $radii[0],      # Radius of gyration to x-axis.
                                        $radii[1],      # Radius of gyration to y-axis.
                                        $radii[2],      # Radius of gyration to z-axis.
                                        $statistics[0], # Mean.
                                        $statistics[2], # STDDEV.
                                        $volume,
                                        $radiusOfVol,
                                        $areaOfRadius));
    }
    ############################################################################
}
################################################################################




### Write out data #############################################################
open(GLOBULAROUT, ">globular.dat") || die "ERROR: Cannot open output file \"globular.dat\": $!\n";
print GLOBULAROUT ("PDB# Chain r_x      r_y      r_z      Mean     STDDEV   Volume   r_V      A_r_V\n");
foreach (@outputGlobular) {
    printf GLOBULAROUT ("%4s %5s %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f\n", $$_{'id'}, , $$_{'chain'}, $$_{'rx'}, $$_{'ry'}, $$_{'rz'}, $$_{'mean'}, $$_{'stddev'}, $$_{'volume'}, $$_{'radiusOfVol'}, $$_{'areaOfRadius'});
}
close(GLOBULAROUT);

open(NONGLOBULAROUT, ">nonglobular.dat") || die "ERROR: Cannot open output file \"nonglobular.dat\": $!\n";
print NONGLOBULAROUT ("PDB# Chain r_x      r_y      r_z      Mean     STDDEV   Volume   r_V      A_r_V\n");
foreach (@outputNonGlobular) {
    printf NONGLOBULAROUT ("%4s %5s %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f %8.5f\n", $$_{'id'}, , $$_{'chain'}, $$_{'rx'}, $$_{'ry'}, $$_{'rz'}, $$_{'mean'}, $$_{'stddev'}, $$_{'volume'}, $$_{'radiusOfVol'}, $$_{'areaOfRadius'});
}
close(NONGLOBULAROUT);
################################################################################
exit;



sub buildHash {
    my %tmpHash = ('id'           => $_[0],
                   'chain'        => $_[1],
                   'rx'           => $_[2],
                   'ry'           => $_[3],
                   'rz'           => $_[4],
                   'mean'         => $_[5],
                   'stddev'       => $_[6],
                   'volume'       => $_[7],
                   'radiusOfVol'  => $_[8],
                   'areaOfRadius' => $_[9]);
    return \%tmpHash;
}



sub readVolumeFile {
    my $volumeFile = shift;
    my $volume;

    open(VOLUMEFILE, "<$volumeFile") || die "ERROR: Cannot open volume XVG file \"$volumeFile\": $!\n";
    while (<VOLUMEFILE>) {
        if ($_ =~ /[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)\s+[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?/) {
            $volume = $2;
        }
    }
    close(VOLUMEFILE);

    return $volume;
}



sub readGyrateFile {
    my $gyrateFile = shift;
    my @radii;

    open(GYRATEFILE, "<$gyrateFile") || die "ERROR: Cannot open radius of gyration XVG file \"$gyrateFile\": $!\n";
    while (<GYRATEFILE>) {
        if ($_ =~ /\d+\s+[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)\s+([-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?)/) {
            $radii[0] = $2;
            $radii[1] = $4;
            $radii[2] = $6;
        }
    }
    close(GYRATEFILE);

    return @radii;
}



sub readPdbIdFile {
    my $pdbIdFile = shift;

    my @pdbIds;
#    @pdbIds = ( { 'id'    => '1MBO',
#                  'chain' => 'A' },
#                { 'id'    => '2AVZ',
#                  'chain' => 'A' },
#                { 'id'    => '4WMT',
#                  'chain' => 'A' },
#                { 'id'    => '2HCO',
#                  'chain' => 'A' },
#                { 'id'    => '1E7I',
#                  'chain' => 'A' } );

    open(PDBIDFILE, "<$pdbIdFile") || die "ERROR: Cannot open PDB ID file \"$pdbIdFile\": $!\n";
    while (<PDBIDFILE>) {
        if ($_ =~ /^\s*([A-Z0-9]{4})\s*([A-Z])/) {
            my %tmpHash = ('id'    => $1,
                           'chain' => $2);
            push(@pdbIds, \%tmpHash);
        }
    }
    close(PDBIDFILE);

    return @pdbIds;
}

################################################################################
### Subroutines ################################################################
################################################################################
sub printHead {
    my @headLines = ("################################################################################",
                     "",
                     "Pachanga $version",
                     ".",
                     "Copyright Thomas H. Schmidt, $year",
                     "",
                     "http://github.com/THSchmidt/dancesteps",
                     "",
                     "This program is part of DanceSteps. DanceSteps is free software.",
                     "DanceSteps comes with ABSOLUTELY NO WARRANTY.",
                     "This is free software, and you are welcome to redistribute it",
                     "under certain conditions; type `--copyright' for details.",
                     "",
                     "################################################################################");
    my $maxLength = 80;
    foreach (@headLines) {
        $maxLength = (length $_ > $maxLength) ? length($_) : $maxLength;
    }

    foreach (@headLines) {
        printf "%s%-${maxLength}s\n", ' ' x int(($maxLength - length($_))/2), $_;
    }
}



sub printFoot {
    print <<EndOfFoot;
Please cite:
  [1] Schmidt, T.H. DanceSteps: Dirty toolkit for Molecular Modeling (Manual)

EndOfFoot
}



sub printHelp {
    my $cmdLParamRef   = shift;
    my $quitAfterPrint = shift;


    print <<EndOfHelp;
DESCRIPTION
-----------
Pachanga reads a list of PDB file IDs (e.g. received from the PISCES server),
downloads each structure, extracts the chains, and analyzes the chain as defined
in the PDB file list using the GROMACS tools gmx sasa and gyrate.
If the molecule exhibits a globular conformation, the resulting volume is used
to compute the diameter.


USAGE: pachanga -f PDBLISTFILE -o OUTPUTFILE

EndOfHelp

    printParamHelp($cmdLParamRef);

    printFoot();

    exit if $quitAfterPrint;
}



sub printCopyright {
    print <<"EndOfCopyright";
This file is part of DanceSteps.

DanceSteps is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
any later version.

DanceSteps is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with DanceSteps; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
EndOfCopyright
    exit;
}

